#Nome da pipeline
name: Execução de Testes Basicos - Scheduler

# em que momento será executada
on:
  schedule:
    - cron: '0 7,14,16,17,20 * * 1-6'    
    
jobs:
  cypress-run:
    # maquina que será executada
    # só teremos um job: rodar os testes
    runs-on: ubuntu-latest #ultima versao do ubunto

    # passo a passo para rodar os testes
    steps:
      # clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v7

      # exemplo de exeucução no terminal
      - name: Instalar dependencias do projetoS
        run: npm install

      # execução e config do projeto
      - name: Execucao de Testes
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # upload do relatório e evidências
      - name: Upload de relatórios e evidências
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Relatórios e Evidências
          path: |
            cypress/reports/html
            cypress/screenshots
            cypress/videos